// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaProspectosC_.Models;

#nullable disable

namespace SistemaProspectosC.Migrations
{
    [DbContext(typeof(ProspectContext))]
    [Migration("20240105195358_keyMigration")]
    partial class keyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SistemaProspectosC_.Models.Documento", b =>
                {
                    b.Property<int>("documentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("prospectoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ruta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("documentoId");

                    b.HasIndex("prospectoID");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SistemaProspectosC_.Models.Prospecto", b =>
                {
                    b.Property<int>("prospectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("codigoPostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("colonia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("estatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("segundoApellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("prospectoId");

                    b.ToTable("Prospectos");
                });

            modelBuilder.Entity("SistemaProspectosC_.Models.Documento", b =>
                {
                    b.HasOne("SistemaProspectosC_.Models.Prospecto", "prospecto")
                        .WithMany("documents")
                        .HasForeignKey("prospectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("prospecto");
                });

            modelBuilder.Entity("SistemaProspectosC_.Models.Prospecto", b =>
                {
                    b.Navigation("documents");
                });
#pragma warning restore 612, 618
        }
    }
}
